// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8Yw2wMz6YwwOEccO_3aVGGlQRwtth1A',
    appId: '1:532873689389:web:30bd3e4c7c5dd6dfc6bba4',
    messagingSenderId: '532873689389',
    projectId: 'getfitt-4239c',
    authDomain: 'getfitt-4239c.firebaseapp.com',
    storageBucket: 'getfitt-4239c.appspot.com',
    measurementId: 'G-S7D5BZX7CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0EDjZCS1uTE5LBZydeOOaJPkGSrxA_k',
    appId: '1:532873689389:android:cb34685fd2d244e8c6bba4',
    messagingSenderId: '532873689389',
    projectId: 'getfitt-4239c',
    storageBucket: 'getfitt-4239c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9UR8OYlJ6njZGAKQ5tYpTp8WfXTsknsA',
    appId: '1:532873689389:ios:00e6990f64408013c6bba4',
    messagingSenderId: '532873689389',
    projectId: 'getfitt-4239c',
    storageBucket: 'getfitt-4239c.appspot.com',
    iosClientId: '532873689389-01qja5udqcuj9djabdjfkp94gd7c0fg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.getfitts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9UR8OYlJ6njZGAKQ5tYpTp8WfXTsknsA',
    appId: '1:532873689389:ios:00e6990f64408013c6bba4',
    messagingSenderId: '532873689389',
    projectId: 'getfitt-4239c',
    storageBucket: 'getfitt-4239c.appspot.com',
    iosClientId: '532873689389-01qja5udqcuj9djabdjfkp94gd7c0fg5.apps.googleusercontent.com',
    iosBundleId: 'com.example.getfitts',
  );
}
